"""Step 1: download a company's filings data from SEC EDGAR (and its peers).

Run:  python 01_fetch_company.py AAPL
      python 01_fetch_company.py AAPL MSFT GOOGL     (first ticker is the subject)
      python 01_fetch_company.py --demo              (invented companies, offline)
      python 01_fetch_company.py AAPL --refresh      (ignore the cache)

EDGAR needs no API key, but the SEC does require you to identify yourself in the
request header. Put your name and email in SEC_USER_AGENT in .env.

Writes data/cache/facts_<TICKER>.json and data/cache/company_index.json.
"""

from __future__ import annotations

import argparse
import json
import random

from sc_common import (CACHE, DEMO_MARKER, EDGAR_BROWSE, SEC_SUBMISSIONS_URL, facts_path,
                       fail, fetch_company_facts, get_json, info, load_ticker_map,
                       price_for, sec_headers, warn)

INDEX_PATH = CACHE / "company_index.json"

DEMO_NOTE = (
    "The facts_*.json files here were GENERATED by 01_fetch_company.py --demo.\n"
    "The companies do not exist and every figure is invented. Nothing derived from\n"
    "them means anything. Delete this folder and fetch real tickers instead.\n"
)

DEMO_COMPANIES = [
    ("DEMOA", "Demo Alpha Manufacturing Inc", 1.0),
    ("DEMOB", "Demo Beta Industries Corp", 0.7),
    ("DEMOC", "Demo Gamma Holdings Ltd", 1.4),
]


def demo_facts(ticker: str, name: str, scale: float) -> dict:
    """Build a companyfacts-shaped payload so the rest of the pipeline can run."""
    rng = random.Random(hash(ticker) % 10_000)
    years = list(range(2016, 2026))
    revenue = 5_000_000_000 * scale
    units_flow, units_instant, units_eps, units_dps, units_shares = [], [], [], [], []
    equity = revenue * 0.6
    shares = 500_000_000 * scale
    for fy in years:
        revenue *= 1 + rng.uniform(0.02, 0.15)
        gross = revenue * rng.uniform(0.35, 0.45)
        operating = revenue * rng.uniform(0.12, 0.20)
        net = operating * rng.uniform(0.70, 0.82)
        ocf = net * rng.uniform(1.05, 1.35)
        capex = revenue * rng.uniform(0.03, 0.06)
        equity += net * 0.6
        shares *= 1 - rng.uniform(0.0, 0.02)
        eps = net / shares
        dps = eps * rng.uniform(0.15, 0.35)
        start, end = f"{fy}-01-01", f"{fy}-12-31"
        base = {"start": start, "end": end, "fy": fy, "fp": "FY", "form": "10-K",
                "accn": f"demo-{fy}"}
        for tag, value in [("revenue", revenue), ("gross", gross), ("op", operating),
                           ("net", net), ("ocf", ocf), ("capex", capex)]:
            units_flow.append({**base, "tag": tag, "val": round(value)})
        units_eps.append({**base, "val": round(eps, 2)})
        units_dps.append({**base, "val": round(dps, 2)})
        units_shares.append({**base, "val": round(shares)})
        inst = {"end": end, "fy": fy, "fp": "FY", "form": "10-K", "accn": f"demo-{fy}"}
        for tag, value in [("assets", equity * 2.1), ("liabilities", equity * 1.1),
                           ("equity", equity), ("cash", revenue * 0.12),
                           ("ltd", revenue * 0.25), ("std", revenue * 0.05)]:
            units_instant.append({**inst, "tag": tag, "val": round(value)})

    def pick(rows, tag):
        return [{k: v for k, v in row.items() if k != "tag"}
                for row in rows if row.get("tag") == tag]

    return {
        "cik": 9_000_000 + abs(hash(ticker)) % 99_999,
        "entityName": name,
        "facts": {"us-gaap": {
            "RevenueFromContractWithCustomerExcludingAssessedTax":
                {"units": {"USD": pick(units_flow, "revenue")}},
            "GrossProfit": {"units": {"USD": pick(units_flow, "gross")}},
            "OperatingIncomeLoss": {"units": {"USD": pick(units_flow, "op")}},
            "NetIncomeLoss": {"units": {"USD": pick(units_flow, "net")}},
            "NetCashProvidedByUsedInOperatingActivities":
                {"units": {"USD": pick(units_flow, "ocf")}},
            "PaymentsToAcquirePropertyPlantAndEquipment":
                {"units": {"USD": pick(units_flow, "capex")}},
            "Assets": {"units": {"USD": pick(units_instant, "assets")}},
            "Liabilities": {"units": {"USD": pick(units_instant, "liabilities")}},
            "StockholdersEquity": {"units": {"USD": pick(units_instant, "equity")}},
            "CashAndCashEquivalentsAtCarryingValue":
                {"units": {"USD": pick(units_instant, "cash")}},
            "LongTermDebtNoncurrent": {"units": {"USD": pick(units_instant, "ltd")}},
            "LongTermDebtCurrent": {"units": {"USD": pick(units_instant, "std")}},
            "EarningsPerShareDiluted": {"units": {"USD/shares": units_eps}},
            "CommonStockDividendsPerShareDeclared": {"units": {"USD/shares": units_dps}},
            "WeightedAverageNumberOfDilutedSharesOutstanding":
                {"units": {"shares": units_shares}},
        }},
    }


def make_demo() -> dict:
    CACHE.mkdir(parents=True, exist_ok=True)
    index = {"subject": DEMO_COMPANIES[0][0], "companies": {}}
    for ticker, name, scale in DEMO_COMPANIES:
        payload = demo_facts(ticker, name, scale)
        facts_path(ticker).write_text(json.dumps(payload), encoding="utf-8")
        index["companies"][ticker] = {
            "cik": payload["cik"], "name": name, "price": round(40 * scale, 2),
            "price_source": "invented", "sic": "3600", "sic_description": "Demo",
            "fiscal_year_end": "1231", "exchange": "DEMO",
            "filings_url": "https://www.sec.gov/edgar/searchedgar/companysearch",
            "latest_10k": None,
        }
    INDEX_PATH.write_text(json.dumps(index, indent=2), encoding="utf-8")
    DEMO_MARKER.write_text(DEMO_NOTE, encoding="utf-8")
    warn("Wrote DEMO companies. They do not exist.")
    return index


def latest_10k(cik: int) -> dict | None:
    """Link to the most recent annual report, the document you actually read."""
    payload = get_json(SEC_SUBMISSIONS_URL.format(cik=cik), headers=sec_headers())
    recent = payload.get("filings", {}).get("recent", {})
    forms = recent.get("form", [])
    for i, form in enumerate(forms):
        if form == "10-K":
            accession = recent["accessionNumber"][i].replace("-", "")
            document = recent["primaryDocument"][i]
            return {
                "filed": recent["filingDate"][i],
                "period": recent.get("reportDate", [None] * len(forms))[i],
                "url": (f"https://www.sec.gov/Archives/edgar/data/{cik}/"
                        f"{accession}/{document}"),
            }
    return None


def company_profile(cik: int) -> dict:
    payload = get_json(SEC_SUBMISSIONS_URL.format(cik=cik), headers=sec_headers())
    exchanges = payload.get("exchanges") or []
    return {
        "sic": payload.get("sic", ""),
        "sic_description": payload.get("sicDescription", ""),
        "fiscal_year_end": payload.get("fiscalYearEnd", ""),
        "exchange": ", ".join(exchanges) if exchanges else "not listed on an exchange",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("tickers", nargs="*", help="subject ticker first, then peers")
    parser.add_argument("--demo", action="store_true", help="invented companies, no network")
    parser.add_argument("--refresh", action="store_true", help="ignore cached filings")
    args = parser.parse_args()

    if args.demo:
        index = make_demo()
        info(f"Demo companies: {', '.join(index['companies'])}")
        print("\nCHECKPOINT: now run  python 02_metrics.py")
        return

    if not args.tickers:
        fail("Give at least one ticker, for example:  python 01_fetch_company.py AAPL MSFT")
    if DEMO_MARKER.exists():
        DEMO_MARKER.unlink()
        warn("Replacing demo data with real filings.")

    tickers = [t.upper() for t in args.tickers]
    mapping = load_ticker_map(refresh=args.refresh)
    unknown = [t for t in tickers if t not in mapping]
    if unknown:
        fail(f"Not in the SEC's ticker list: {', '.join(unknown)}\n"
             "Foreign companies filing 20-F and OTC/pink-sheet shells often are not. "
             "Check the spelling at https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany")

    index = {"subject": tickers[0], "companies": {}}
    for ticker in tickers:
        cik = mapping[ticker]["cik"]
        name = mapping[ticker]["title"]
        path = facts_path(ticker)
        if path.exists() and not args.refresh:
            info(f"{ticker}: using cached filings ({path.name})")
        else:
            payload = fetch_company_facts(ticker, cik)
            path.write_text(json.dumps(payload), encoding="utf-8")
            info(f"{ticker}: downloaded XBRL facts ({path.stat().st_size / 1e6:.1f} MB)")
        profile = company_profile(cik)
        filing = latest_10k(cik)
        price, source = price_for(ticker)
        if price is None:
            warn(f"{ticker}: no price. Valuation ratios will be blank. Add a row to "
                 "data/prices_manual.csv or set ALPHAVANTAGE_API_KEY in .env.")
        index["companies"][ticker] = {
            "cik": cik, "name": name, "price": price, "price_source": source,
            "filings_url": EDGAR_BROWSE.format(cik=cik), "latest_10k": filing,
            **profile,
        }
        bits = [f"{ticker}: {name}", profile.get("sic_description") or "",
                profile.get("exchange") or ""]
        info(" | ".join(b for b in bits if b))
        if filing:
            info(f"{ticker}: latest 10-K filed {filing['filed']}")

    INDEX_PATH.write_text(json.dumps(index, indent=2), encoding="utf-8")
    financial = [t for t, c in index["companies"].items()
                 if str(c.get("sic", "")).startswith(("60", "61", "62", "63", "64"))]
    if financial:
        warn(f"{', '.join(financial)} looks like a bank, insurer or other financial firm. "
             "Debt and return ratios do not mean the same thing there - see "
             "docs/methodology.md.")
    print("\nCHECKPOINT: the company name and exchange above should match what you "
          "expected. Then run:  python 02_metrics.py")


if __name__ == "__main__":
    main()
